app = "uncertainty-study"
primary_region = "bos"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true