# fly.toml app configuration file generated for uncertainty-study on 2025-04-07T00:23:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

app = 'uncertainty-study'
primary_region = 'bos'

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  cpu_count = 1  # or 1
  memory = "256mb"  # Add this line
